name: Docker Image CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3

      - name: Pre-commit actions
        uses: pre-commit/action@v3.0.0

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag frontend:$(date +%s)
